/**
 * Query layer — re-exports from the pure-JS JSON data store.
 * This keeps the existing import paths (`@/lib/queries`) working
 * while avoiding the native `better-sqlite3` compilation requirement.
 */
export {
  getCandidates,
  getCandidate,
  getCountries,
  getCountry,
  getCountryVisa,
  getCountryLivingCosts,
  getCountryStudentJobs,
  getCountryGraduateVisa,
  getCountryScholarships,
  getCountryCities,
  getSchools,
  getSchoolsByCountry,
  getSchool,
  getSchoolPrograms,
  getSchoolAdmission,
  getSchoolDeadlines,
  getProgramDeadlines,
  getSchoolContacts,
  getProgramSources,
  getAuditReport,
  getDatabaseMetadata,
  getCandidateScores,
  getScoreForSchool,
  getCity,
  getRelevantPrograms,
  getSchoolsWithScores,
  getSchoolsByCountryWithScores,
  getCountryBySchoolId,
  getCityBySchoolId,
  getFilteredSchools,
  parseTuition,
  getMinTuitionForSchool,
  getMinTuitionForSchoolByCandidate,
  formatTuition,
  getProgramById,
  getSchoolById,
} from "./data-store";

export {
  getPhdOffers,
  getPhdOffer,
  getPhdCountries,
  getPhdFundingTypes,
  getPhdDomains,
  getFilteredPhdOffers,
  formatFundingType,
  fundingBadgeStyle,
  PHD_COUNTRY_META,
} from "./phd-store";

export type { PhdOffer, PhdFilterCriteria, PhdSupervisor } from "./phd-store";

export type {
  Candidate,
  Country,
  City,
  School,
  Program,
  Admission,
  Visa,
  Scholarship,
  LivingCost,
  StudentJob,
  GraduateVisa,
  Deadline,
  CandidateScore,
  FilterCriteria,
  FilteredSchoolResult,
  VerificationStatus,
  DataSource,
  ProgramDeadline,
  Contact,
  AuditFlag,
  AuditReport,
} from "./data-store";