services:
  - type: web
    name: masters-finder
    runtime: node
    plan: free
    buildCommand: npm install; npm run build
    startCommand: npx next start -H 0.0.0.0 -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
